#name: Build and Deploy
#
#on: [push]
#
#jobs:
#
#  build-and-deploy:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout Repo
#        uses: actions/checkout@v2
#        
#      - name: Install Dependencies
#        run: sudo apt install python2;sudo npm install -g n;sudo n 14.16.1;npm install

      #- name: Build
      #  run: npm run build
        
#      - name: Deploy to AWS S3
#        uses: jakejarvis/s3-sync-action@master
#        with:
#          args: --acl public-read --follow-symlinks --delete
#        env:
#          AWS_S3_BUCKET: 'dev-epi-frontend'
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          AWS_REGION: 'ap-southeast-2'   # optional: defaults to us-east-1

